### ISSUE TITLE
Assert error in vmod_clean()

### ISSUE THREAD

**Issue by nitram2k** [lkarsten/libvmod-cookie#34]
Hello,

I just installed this vmod and I get the following error in about 75% of all requests:

Assert error in vmod_clean(), vmod_cookie.c line 233:
  Condition((cookie)->magic == 0x3BB41543) not true.
thread = (cache-worker)
version = varnish-4.0.3 revision b8c4a34
ident = Linux,2.6.32-504.16.2.el6.x86_64,x86_64,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x431c15: /usr/sbin/varnishd() [0x431c15]
  0x7f6d689d14bf: /usr/lib64/varnish/vmods/libvmod_cookie.so(vmod_clean+0xaf) [0x7f6d689d14bf]
  0x7f6d689d1db7: /usr/lib64/varnish/vmods/libvmod_cookie.so(vmod_parse+0x37) [0x7f6d689d1db7]
  0x7f6d68fefeed: ./vcl.JR78CKAF.so(VGC_function_vcl_recv+0x3ed) [0x7f6d68fefeed]
  0x43e172: /usr/sbin/varnishd() [0x43e172]
  0x43f565: /usr/sbin/varnishd(VCL_recv_method+0x45) [0x43f565]
  0x4372ca: /usr/sbin/varnishd(CNT_Request+0x5ca) [0x4372ca]
  0x42c17b: /usr/sbin/varnishd(HTTP1_Session+0x56b) [0x42c17b]
  0x43ab18: /usr/sbin/varnishd() [0x43ab18]
  0x434695: /usr/sbin/varnishd(Pool_Work_Thread+0x365) [0x434695]
req = 0x7f6d6dadb020 {
  sp = 0x7f6d6783f1a0, vxid = 1073774596,  step = R_STP_RECV,
  req_body = R_BODY_NONE,
  restarts = 0, esi_level = 0,
  sp = 0x7f6d6783f1a0 {
    fd = 13, vxid = 32769,
    client = 87.213.97.22 50015,
    step = S_STP_WORKING,
  },
  worker = 0x7f6d6343ac10 {
    ws = 0x7f6d6343ae30 {
      id = "wrk",
      {s,f,r,e} = {0x7f6d6343a400,0x7f6d6343a400,(nil),+2048},
    },
  VCL::method = RECV,
  VCL::return = abandon,
  },
  ws = 0x7f6d6dadb1b8 {
    id = "req",
    {s,f,r,e} = {0x7f6d6dadd010,+2584,(nil),+253968},
  },

I tried setting -p workspace_client=96K or even -p workspace_client=256K but that doesn't help much.. 

I am using the latest version (I think, i used this url: https://github.com/lkarsten/libvmod-cookie/archive/4.0.zip)

Any ideas? Thanks! :)

**Comment by lkarsten** [comment]
Hi. Please try latest master (3a2a9ae).

**Comment by lkarsten** [comment]
Sorry, that is of course HEAD on the 4.0 branch.

**Comment by nitram2k** [comment]
I've just tried the latest master and it seems to be fixed!

**Comment by lkarsten** [comment]
Sweet. I'm closing this now, open a fresh issue if the problem reappears.
