### ISSUE TITLE
Assert in vmod_clean

### ISSUE THREAD

**Issue by terbolous** [lkarsten/libvmod-cookie#35]
Child (23192) died signal=6 (core dumped)
Child (23192) Panic message:
Assert error in vmod_clean(), vmod_cookie.c line 233:
  Condition((cookie)->magic == 0x3BB41543) not true.
thread = (cache-worker)
version = varnish-4.0.3 revision b8c4a34
ident = Linux,2.6.32-504.el6.x86_64,x86_64,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x431c15: /usr/sbin/varnishd() [0x431c15]
  0x7ff9ccaed3ef: /usr/lib64/varnish/vmods/libvmod_cookie.so(vmod_clean+0xaf) [0x7ff9ccaed3ef]
  0x7ff9ccaedf3a: /usr/lib64/varnish/vmods/libvmod_cookie.so(vmod_parse+0x4a) [0x7ff9ccaedf3a]
  0x7ff9cccf2f22: ./vcl.RMFhp7Mo.so(VGC_function_vcl_recv+0x1f2) [0x7ff9cccf2f22]
  0x43e172: /usr/sbin/varnishd() [0x43e172]
  0x43f565: /usr/sbin/varnishd(VCL_recv_method+0x45) [0x43f565]
  0x4372ca: /usr/sbin/varnishd(CNT_Request+0x5ca) [0x4372ca]
  0x42c17b: /usr/sbin/varnishd(HTTP1_Session+0x56b) [0x42c17b]
  0x43ab18: /usr/sbin/varnishd() [0x43ab18]
  0x434695: /usr/sbin/varnishd(Pool_Work_Thread+0x365) [0x434695]
req = 0x7ff9c609b020 {
  sp = 0x7ff9c441afe0, vxid = 1073774600,  step = R_STP_RECV,
  req_body = R_BODY_NONE,
  restarts = 0, esi_level = 0,
  sp = 0x7ff9c441afe0 {
    fd = 14, vxid = 65537,
    client = 127.0.0.1 39481,
    step = S_STP_WORKING,
  },
  worker = 0x7ff9c3249c10 {
    ws = 0x7ff9c3249e30 {
      id = "wrk",
      {s,f,r,e} = {0x7ff9c3249400,0x7ff9c3249400,(nil),+2048},
    },
  VCL::method = RECV,
  VCL::return = abandon,
  },
  ws = 0x7ff9c609b1b8 {
    id = "req",
    {s,f,r,e} = {0x7ff9c609d010,+1008,(nil),+57360},
  },
  http[req] = {
    ws = 0x7ff9c609b1b8[req]
      "GET",
      "/WebResource.axd?d=6JkJ7du29aJvrAL3cPzeAMkmqoZHOmy1tIh6FujyhuCFn9uRT5zgjxupebDechfQuz8Uryr-BxplOgKek3jFXM_FssJH9zkWNhEXwGaz_uw1&t=635588654815688065",
      "HTTP/1.1",
      "Host: statistikkportalen.XXX.no",
      "Connection: keep-alive",
      "Cache-Control: max-age=0",
      "Accept: */*",
      "If-Modified-Since: Fri, 06 Feb 2015 23:24:41 GMT",
      "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36",
      "Referer: https://statistikkportalen.XXX.no/Pages/default.aspx",
      "Accept-Encoding: gzip, deflate, sdch",
      "Accept-Language: en-US,en;q=0.8,nb;q=0.6",
      "Cookie: __utma=96641627.1805302195.1410765487.1417038264.1417693820.5; WT_FPC=id=153.110.241.229-89042160.30424790:lv=1422907049355:ss=1422905138414; _ga=GA1.2.1805302195.1410765487; WSS_FullScreenMode=false",
      "X-Forwarded-Proto: https",
      "X-SSL-cipher: DHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(128) Mac=AEAD",
      "X-Forwarded-For: 195.254.193.39, 127.0.0.1",
  },
  vcl = {
    srcname = {
      "input",
      "Builtin",
      "/opt/etc/varnish/backends.vcl",
      "/opt/etc/varnish/statistikkportalen/vcl_recv.vcl",
      "/opt/etc/varnish/statistikkportalen/vcl_backend_response.vcl",
    },
  },
},

VCL related to cookie handling (if it matters):
# Parse cookies
if (req.http.Cookie) {
    cookie.parse(req.http.Cookie);
    if (cookie.get("STATISTIKKCOOKIE")) {
        set req.http.X-Tracker = cookie.get("STATISTIKKCOOKIE");
    }
}

if (! req.http.X-Tracker) {
  if (req.http.X-Forwarded-For) {
    set req.http.X-Tracker = req.http.X-Forwarded-For;
  } else {
    set req.http.X-Tracker = client.ip;
  }

}

# Set site backend, hash key is cookie value, this should ensure sticky session
set req.backend_hint = statistikkportalen.backend(req.http.X-Tracker);

**Comment by lkarsten** [comment]
Hi. Please try latest master (3a2a9ae).

**Comment by terbolous** [comment]
With my so far limited testing, I have not been able to reproduce after the proposed fix.

**Comment by lkarsten** [comment]
Thanks for the feedback. I'm closing this issue now, please open a new one if the problem reappears.
