### ISSUE TITLE
Assert error in vmod_clean(), vmod_cookie.c line 233:

### ISSUE THREAD

**Issue by perbu** [lkarsten/libvmod-cookie#36]
Package: varnish-plus-vmods-0.20150327-1.el7.x86_64

Last panic at: Thu, 25 Jun 2015 14:56:54 GMT
Assert error in vmod_clean(), vmod_cookie.c line 233:
  Condition((cookie)->magic == 0x3BB41543) not true.
thread = (cache-worker)
version = varnish-plus-4.0.3r3 revision 7ddde37
ident = Linux,3.10.0-229.7.2.el7.x86_64,x86_64,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x438b3d: pan_ic+0x14d
  0x7f9e2b8e5b3b: /usr/lib64/varnish-plus/vmods/libvmod_cookie.so(vmod_clean+0xab) [0x7f9e2b8e5b3b]
  0x7f9e2b8e5bfe: /usr/lib64/varnish-plus/vmods/libvmod_cookie.so(vmod_parse+0x4e) [0x7f9e2b8e5bfe]
  0x7f9e2bcf1cb1: ./vcl.bK8A1fAT.so(VGC_function_vcl_recv+0x31) [0x7f9e2bcf1cb1]
  0x445ffc: vcl_call_method+0x1bc
  0x4464b5: VCL_recv_method+0x45
  0x43de56: CNT_Request+0x956
  0x4329b3: HTTP1_Session+0x773
  0x441cf7: ses_req_pool_task+0x67
  0x43bea2: Pool_Work_Thread+0x392
req = 0x7f9e275b0020 {
  sp = 0x7f9e3627e320, vxid = 1073774596,  step = R_STP_RECV,
  req_body = R_BODY_NONE,
  restarts = 0, esi_level = 0,
  sp = 0x7f9e3627e320 {
    fd = 14, vxid = 32769,
    client = 10.0.2.2 63963,
    step = S_STP_WORKING,
  },
  worker = 0x7f9e27ba7b50 {
    ws = 0x7f9e27ba7d70 {
      id = "wrk",
      {s,f,r,e} = {0x7f9e27ba7350,0x7f9e27ba7350,(nil),+2048},
    },
  VCL::method = RECV,
  VCL::return = abandon,
  },
  ws = 0x7f9e275b01c0 {
    id = "req",
    {s,f,r,e} = {0x7f9e275b2018,+464,(nil),+57352},
  },
  http[req] = {
    step = S_STP_WORKING,
  },
  worker = 0x7f9e27ba7b50 {
    ws = 0x7f9e27ba7d70 {
      id = "wrk",
      {s,f,r,e} = {0x7f9e27ba7350,0x7f9e27ba7350,(nil),+2048},
    },
  VCL::method = RECV,
  VCL::return = abandon,
  },
  ws = 0x7f9e275b01c0 {
    id = "req",
    {s,f,r,e} = {0x7f9e275b2018,+464,(nil),+57352},
  },
  http[req] = {
    ws = 0x7f9e275b01c0[req]
      "GET",
      "/",
      "HTTP/1.1",
      "Host: localhost:8080",
      "Connection: keep-alive",
      "Cache-Control: max-age=0",
      "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36",
      "Accept-Encoding: gzip, deflate, sdch",
      "Accept-Language: en-US,en;q=0.8,nb;q=0.6,da;q=0.4,sv;q=0.2",
      "Cookie: abgroup=A",
      "X-Forwarded-For: 10.0.2.2",
  },
  vcl = {
    srcname = {
      "input",
      "Builtin",
    },
  },
},

VCL: 
sub vcl_recv {
    cookie.parse(req.http.Cookie);
    set req.http.abgroup = cookie.get("abgroup");

    if (! req.http.abgroup) {
        if (std.random(0, 99) < 50) {
            # A group
            set req.http.abgroup = "A";
        } else {
            # B group
            set req.http.abgroup = "B";
        }
    }
}

..

sub vcl_deliver {
    if (req.http.abgroup) {
        # set resp.http.Set-Cookie = "abgroup=" + req.http.abgroup + "; Expires=" + cookie.format_rfc1123(now, 10m) + "; httpOnly";
    }

}

**Comment by perbu** [comment]
I am unable to reproduce the issue after a restart. Something weird is going on.

**Comment by lkarsten** [comment]
I believe this is related to waitinglist handling. Fix is commited, please use at least 71ca839.
